# Generated by Django 4.2 on 2023-04-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0004_delete_contact_remove_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_date',
        ),
    ]
