# Generated by Django 4.2 on 2023-04-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0006_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
